#!/usr/bin/env bash
# script that transfer a file from client to server using scp
if [ $# -lt 3 ]; then
    echo "0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    $0 -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
fi