#!/usr/bin/env bash
# installing nginx | put a text inside file of nginx | start nginx
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
