#!/usr/bin/env bash
# installing nginx
# put a text inside file of nginx
# start nginx
# redirection
sudo apt-get -y update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get install -y haproxy=2.0\*
sudo cp /etc/haproxy/haproxy.cfg
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
cat >> /etc/haproxy/haproxy.cfg << EOF
frontend firstbalance
        bind *:80
        option forwardfor
        default_backend webservers
backend webservers
        balance roundrobin
        server webserver1 1430-web-02-34.73.23.14:80
        server webserver2 1430-web-02-34.73.23.14:80
        server webserver1 1430-web-02-34.73.23.14:80 check
        server webserver2 1430-web-01-34.74.192.102:80 check
EOF
sudo service haproxy restart
