#!/usr/bin/env bash
# change nginx configuration so it listen to port 80
sudo nginx stop
sudo pkill nginx
sed  -i 's/listen 80;listen 8080/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
